exclude: ^(notebooks|logs)/
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: [--cache]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
        description: Check for files that would conflict on a case-insensitive filesystem
      - id: check-docstring-first
        description: Check that the first line of a Python file is a docstring or a comment
      - id: check-merge-conflict
        description: Check for merge conflicts
      - id: check-toml
        description: Check TOML files for syntax errors
      - id: end-of-file-fixer
        description: Ensure files end with a newline character
      - id: mixed-line-ending
        args: [--fix=lf]
        description: Check for mixed line endings and fix them to LF
      - id: trailing-whitespace
        description: Check for trailing whitespace and fix it
      - id: check-added-large-files
        description: Check for large files added to the repository
      - id: check-symlinks
        description: Check for symbolic links which do not point to anything
      - id: detect-private-key
        description: Check for private keys in the repository
