[build-system]
requires = ["setuptools >= 64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jaxili"
version = "0.1.4"
authors = [{name = "Sacha Guerrini"}]
description = "This package provides tools to execute and implement Implicit Likelihood Inference tools in JAX."
dependencies = [
    "numpy",
    "jupyter",
    "matplotlib",
    "cmake",
    "tensorflow-cpu==2.18.0",
    "tensorflow-probability",
    "getdist",
    "jax",
    "jax_dataloader",
    "datasets==3.5.0",
    "optax",
    "distrax",
    "flax",
    "optuna",
    "orbax-checkpoint==0.11.6",
    "numpyro",
    "flowMC",
    "tarp",
    "deprecation"
]
readme = "README.md"
requires-python = ">=3.10, <3.13"
urls = {Repository = "https://github.com/sachaguer/jaxili"}

[project.optional-dependencies]
cuda = [
    "jax[cuda12]"
]

docs = [
    "myst-parser",
    "numpydoc",
    "sphinx",
    "sphinx-book-theme",
    "nbsphinx",
    "tf-keras"
]

test = [
    "pytest>=7.4,<8",
    "pytest-cov",
    "pytest-emoji",
    "pytest-pydocstyle>=0.0.7",
    "tf-keras",
    "sbibm",
    "sbi==0.23.3",
    "torch"
]

lint = ["black", "isort"]
release = ["build", "twine"]

#Install for development
dev = ["jaxili[docs,lint,release,test,cuda]", "pre-commit"]

[tool.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
addopts = ["--verbose"]
testpaths = ["jaxili"]

[tool.setuptools.packages.find]
where = ["."]
include = ["jaxili*"]
exclude = ["jaxili.tests*", "jaxili.notebooks*"]

[tool.ruff]
# We use ruff to lint and auto-format code

# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
  "*.ipynb",            # ignore jupyter notebooks completely for now
]

# more lenient line width than Black
line-length = 120
indent-width = 4

# minimum target python version
target-version = "py311"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]

"__init__.py" = [
  "F401", # unused imports
]

"tests/**/__init__.py" = [
  "F403", # * imports
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
